services:
  db:
    image: mysql:8.0
    container_name: mystery-db
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: mystery_game
      MYSQL_USER: gantaro
      MYSQL_PASSWORD: gan70668
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db-data:/var/lib/mysql